apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spark.fullname" . }}-profile
  labels:
    {{- include "spark.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spark.selectorLabels" . | nindent 6 }}
      microservice: profile
  template:
    metadata:
      {{- with .Values.profile.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spark.labels" . | nindent 8 }}
        {{- with .Values.profile.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        microservice: profile
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spark.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.profile.image.repository }}:{{ .Values.profile.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.profile.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.profile.service.port }}
              protocol: TCP
          env:
            {{- include "quarkus.datasource" . }}
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value:  {{ .Values.oidc.authserverurl }}
            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              value:  {{ .Values.oidc.secret }}
            - name: QUARKUS_OIDC_CLIENT_ID
              value:  {{ .Values.oidc.clientid }}
            - name: QUARKUS_OIDC_LOGOUT_EXTRA_PARAMS_CLIENT_ID
              value:  {{ .Values.oidc.clientid }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Release.Name }}-{{ .Values.kafka.service.name }}:{{ .Values.kafka.service.port }}"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
