version: "3.8"
services:
  associations:
    # image: registry.gitlab.unige.ch/p-info-2024/p-info-1/associations:latest
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://spark:5432/spark
      QUARKUS_DATASOURCE_USERNAME: pinfo1
      QUARKUS_DATASOURCE_PASSWORD: pinfo1
    ports:
      - 8080:8080

  spark:
    image: postgres
    environment: 
      POSTGRES_USER: pinfo1
      POSTGRES_PASSWORD: pinfo1
      POSTGRES_DB: spark
    ports:
      - 5432:5432
  
  kafka:
    image: bitnami/kafka
    volumes:
      - kafka:/bitnami/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

volumes:
  kafka:
