version: "3.8"
services:
  events:
    # image: registry.gitlab.unige.ch/p-info-2024/p-info-1/events:latest
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://spark:5432/spark
      QUARKUS_DATASOURCE_USERNAME: pinfo1
      QUARKUS_DATASOURCE_PASSWORD: pinfo1
    ports:
      - 8080:8080

  spark:
    image: postgres
    environment: 
      POSTGRES_USER: pinfo1
      POSTGRES_PASSWORD: pinfo1
      POSTGRES_DB: spark
    ports:
      - 5432:5432